# class name

In [1]:
def test():
    print('Test() for function')
    return
test()

Test() for function


In [3]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
    
obj=Demo()
obj.test()

test() for the class and method


In [7]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=Demo1()
print(p1.fact(5))

120


In [8]:
# def test(self,para1,para2)

In [1]:
class Demo2:
    def accept(self,p1,p2):
        self.a=p1
        self.b=p2
        return
    def display(s):
        print("p1= ",s.a)
        print("p2= ",s.b)
        
p=Demo2()
p.accept(5,8)
p.display()

p1=  5
p2=  8


In [3]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self):
        return self.p1+self.p2
    
c1=Demo2(10,20)
print(c1.add())

30


In [1]:
import re
sum=0
pattern='back'
if re.match(pattern,'backup.txt'):
    sum+=1
if re.match(pattern,'text.back'):
    sum+=2
if re.match(pattern,'backup.txt'):
    sum+=4
if re.match(pattern,'text.back'):
    sum+=8

print(sum)

5


In [4]:
# some inheritance

In [5]:
class Person():
    #Contructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
    
# Derived Class
class Employee(Person):
    def isEmployee(self):
        return True
    
emp=Person("Ank")
print(emp.getName(),emp.isEmployee())

emp1=Employee("Sra")
print(emp1.getName(),emp1.isEmployee())


Ank False
Sra True


# python Numpy

In [6]:
lst = [1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [2]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [3]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [4]:
lst=[1.0,2.5,3.6,9.4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [8]:
# Re-shape the given array
# numpy.reshape(arrayName,reshape,order='C')

In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
#np.ones(shape,dtype=float,order='c')

In [14]:
A=np.ones((4,3),dtype=np.int64)
print(A)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)


[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [3]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)


[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [5]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [7]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [8]:
# Indexing and slicing of Numpy

In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [10]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Row: ",a1[0])

First Row:  [1 2 3]


In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second Row: ",a1[1])

Second Row:  [4 5 6]


In [12]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column: ",a1[:,1])

Slicing Column:  [2 5]


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column: ",a1[:,2])

Slicing Last Column:  [3 6]


In [ ]:
Some math Operations on the given Random No
Min -- returns the least no
Max -- return the largest no
Mean -- Mean
Median -- Median
GD -- Gaussian Distribution

In [14]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min Value =",np.min(a1))
print("Max Value =",np.max(a1))
print("Mean Value =",np.mean(a1))
print("Median Value =",np.median(a1))

[5.07256213 5.14460662 5.22096216 5.22701094 4.68553479 5.74720143
 6.1249477  4.52172703 3.40625875 4.1633835 ]
Min Value = 3.406258749265866
Max Value = 6.124947700507679
Mean Value = 4.931419505223361
Median Value = 5.108584375217903


In [16]:
# multiply of 1D arrays
# numpy.dot(x,y) 

In [17]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [18]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [19]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])